language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
addons:
  apt:
    packages:
    - graphviz
install:
- pip install Sphinx codecov packaging
- 'python -c $''import os, packaging.version as version\nv = version.parse(os.environ.get("TRAVIS_TAG",
  "1.0")).public\nwith open("VERSION", "w") as f: f.write(v)'''
- pip install -e .[test]
- cd docs
- make clean html
- cd ..
script:
- |
  if [[ "$TRAVIS_PYTHON_VERSION" = '3.7' ]]; then
    pytest --cov=graphtik -m 'slow or not slow'
  else
    # Undo configs in setup.cfg
    echo -e '[pytest]\nmarkers: slow' > pytest.ini
    pytest --cov=graphtik
  fi
deploy:
  provider: pypi
  user: __token__
  password:
    secure: BGZ0hMf/qY8PcN7qqS//xO/t/MCJytkBYFwgMlJeFPJqpS6cdJSxnZ2hA1edlcQPZ4TzwmHBr9TKurGQBzirYeqU+kEWE8L0YMIHasxprf8lruPqdNNJ9gT2gNXKbx+YNS4PcWHAc18g4oSqfEbc29EfOVWzW0MWuJhlK9b87lNa8wJnRkyYmFlyRHhmAOd0b4IGtiA0hDzyDfhXxMUpuW18Ms5rN/MT3hZRKCzY0Ec1cDINtKUNB+rPcu9QB1KviQq8XUBTiyeOIiRFN0XJb3MzxRlc47z1Iskx2PmVBfG9RrBYfaVQNLGKEbX9kvNYsK/0IQ5jSIl5n2jxGbC/XIOZ1fM4CY/p4GGhxFDPhcIwPkxLDaZ1PPOt8KqmfGiR1W7J4CZIo481qlNIB283GisDnQ8FM1dcFerXtbXHiw9bGwX+RlwW0ldqASQWwYBpZgpK88Ut7i7Aa+o7e9olxgVAC1NYMnblihRhdInLipDEfYnX8R28f1xuK2VlZXxrqENBxwupSyyH78IWobe01CCc4+qHbnJMA9hsdGCGkX9QU1lyzNurRF/1CYaVnsKR0/3jwW/3NkyFsGsKP/vYGG9mMyyTfSNEYCk3BtpiyBeWEpi/qNIoQhb/dK2dfYpB/EyRnH3yDjN8m3cEmnnqOTwJTDelrNyQX0b6MNxc0T8=
  on:
    repo: pygraphkit/graphtik
    branch: publish
    tags: true
    python: 3.7
after_success:
- codecov
