language: python
python:
- '3.6'
- '3.7'
addons:
  apt:
    packages:
    - graphviz
install:
- pip install Sphinx codecov packaging
- 'python -c $''import os, packaging.version as version\nv = version.parse(os.environ.get("TRAVIS_TAG",
  "1.0")).public\nwith open("VERSION", "w") as f: f.write(v)'''
- pip install -e .[test]
- cd docs
- make clean html
- cd ..
script:
- |
  if [[ "$TRAVIS_PYTHON_VERSION" = '3.7' ]]; then
    pytest --cov=graphtik -m 'slow or not slow' --log-level=DEBUG
  else
    # Undo configs in setup.cfg
    echo -e '[pytest]\nmarkers: slow' > pytest.ini
    pytest  --log-level=DEBUG --cov=graphtik
  fi
deploy:
  provider: pypi
  user: __token__
  password:
    secure: tgBLsQZAUUuaWOtcm9UcVqByPCQCguOJw/TuqVDXfuUQiAPhD0ipKnPsqGnzbcG5gckKxqIUqWdIA5/jgkyJfnUWgqeiIAdyaKzcnk5XVX+yHC3GP8HP7z9oX9x8Gm860/yVzhpmD3oTo8aFbHofymflpYu7OvQ3q9JtFI+6oq02SZ1zWMfOkivF74R44HN3f5Rd8IuOvaJMiS0GvH3UFrxlmsvZ5x5b35L8stBmq8hvnr7HrwyeBVa7YCydKwHMP5zvYbsV43AAGOgukGmR5qGnf8U8uxrJoF52GHlNIUz1FZ+Lom5v9h9ajWaDkLm6d73OB6Q9koQAJx+fNX/NpSkOSDJpJzKPl6yEhcJHo8OBpI8l3yyo7CZJkLBN5JjVHMpyiU208ueq8hhTJYtecvab5OMbwRg2KMnRn3Ettspj9CFKURsyoLfqndn/7rnlPc3SNWSF2Qp0nh4fNUSl9T7C3vyofkENxN0SARK6VCsBn0/CQYaiBnYUEUanCszn51jD7B+Vt1HnSrIoC6tDri3lRhQIyQBmRmUnUCZNedcP1VuzonvOzMK1ngS2iwcyLHgPko21Io6WZiLp4351epFKsBPqJl9s/gyHWxJ+LRxlHpfsPlVyxy4mANKtejhtVTALQ/J6gCQxsBMh9JpKwJ7u4tVKhsWvFtPXUZyoB1E=
  on:
    repo: pygraphkit/graphtik
    branch: publish
    tags: true
    python: 3.7
after_success:
- codecov
